#!/usr/bin/env bash
set -euo pipefail

secret_root="${1:-${CI_SECRET_ROOT:-$HOME/workspace/build-automation}}"

mkdir -p \
  "$secret_root/shared" \
  "$secret_root/profiles/actionfit/android" \
  "$secret_root/profiles/actionfit/ios" \
  "$secret_root/profiles/actionfit/ios/profiles" \
  "$secret_root/profiles/stormborn/android" \
  "$secret_root/profiles/stormborn/ios" \
  "$secret_root/profiles/stormborn/ios/profiles"

write_if_missing() {
  local path="$1"
  shift
  if [ -f "$path" ]; then
    echo "exists: $path"
    return
  fi

  printf '%s\n' "$@" > "$path"
  echo "created: $path"
}

write_if_missing "$secret_root/shared/android-signing.env" \
  "# Shared Android signing passwords for this project." \
  "# Profile files can override these values when a company/account uses different passwords." \
  "ANDROID_KEYSTORE_PASS=\"\"" \
  "ANDROID_KEYALIAS_PASS=\"\""

write_if_missing "$secret_root/profiles/actionfit/android-signing.env" \
  "# Optional Android signing password override for Actionfit." \
  "# Leave these commented to use shared/android-signing.env." \
  "# ANDROID_KEYSTORE_PASS=\"\"" \
  "# ANDROID_KEYALIAS_PASS=\"\""

write_if_missing "$secret_root/profiles/stormborn/android-signing.env" \
  "# Optional Android signing password override for Stormborn." \
  "# Leave these commented to use shared/android-signing.env." \
  "# ANDROID_KEYSTORE_PASS=\"\"" \
  "# ANDROID_KEYALIAS_PASS=\"\""

write_if_missing "$secret_root/shared/ios-keychain.env" \
  "# Optional password for the temporary keychain created by the iOS workflow." \
  "# Leave IOS_KEYCHAIN_PASSWORD blank to let the workflow generate a per-run password." \
  "# Leave IOS_KEYCHAIN_PATH blank to let the workflow create a per-run temporary keychain." \
  "IOS_KEYCHAIN_PASSWORD=\"\"" \
  "IOS_KEYCHAIN_PATH=\"\""

write_if_missing "$secret_root/shared/github-package-read-token" \
  "# Optional GitHub read token for private UPM package repositories." \
  "# Prefer gh auth setup-git on the runner user. If that is unavailable, put one fine-grained token on the first non-comment line." \
  "# Required access: read-only Contents access to private ActionFit package repositories."

write_if_missing "$secret_root/profiles/actionfit/profile.env" \
  "ANDROID_KEYSTORE_PATH=\"$secret_root/profiles/actionfit/android/upload.keystore\"" \
  "GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_PATH=\"$secret_root/profiles/actionfit/android/google-play-service-account.json\"" \
  "IOS_DEVELOPMENT_TEAM_ID=\"49W7A8489P\"" \
  "APP_STORE_CONNECT_API_KEY_ID=\"\"" \
  "APP_STORE_CONNECT_ISSUER_ID=\"\"" \
  "APP_STORE_CONNECT_API_KEY_P8_PATH=\"$secret_root/profiles/actionfit/ios/AuthKey_Actionfit.p8\"" \
  "IOS_DISTRIBUTION_CERTIFICATE_P12_PATH=\"$secret_root/profiles/actionfit/ios/AppleDistribution_Actionfit.p12\"" \
  "IOS_DISTRIBUTION_CERTIFICATE_PASSWORD=\"\"" \
  "IOS_APP_STORE_PROVISIONING_PROFILE_DIR=\"$secret_root/profiles/actionfit/ios/profiles\"" \
  "IOS_PROVISIONING_PROFILE_AUTO_GENERATE=\"true\""

write_if_missing "$secret_root/profiles/stormborn/profile.env" \
  "ANDROID_KEYSTORE_PATH=\"$secret_root/profiles/stormborn/android/upload.keystore\"" \
  "GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_PATH=\"$secret_root/profiles/stormborn/android/google-play-service-account.json\"" \
  "IOS_DEVELOPMENT_TEAM_ID=\"\"" \
  "APP_STORE_CONNECT_API_KEY_ID=\"\"" \
  "APP_STORE_CONNECT_ISSUER_ID=\"\"" \
  "APP_STORE_CONNECT_API_KEY_P8_PATH=\"$secret_root/profiles/stormborn/ios/AuthKey_Stormborn.p8\"" \
  "IOS_DISTRIBUTION_CERTIFICATE_P12_PATH=\"$secret_root/profiles/stormborn/ios/AppleDistribution_Stormborn.p12\"" \
  "IOS_DISTRIBUTION_CERTIFICATE_PASSWORD=\"\"" \
  "IOS_APP_STORE_PROVISIONING_PROFILE_DIR=\"$secret_root/profiles/stormborn/ios/profiles\"" \
  "IOS_PROVISIONING_PROFILE_AUTO_GENERATE=\"true\""

find "$secret_root" -type d -exec chmod 700 {} \;
find "$secret_root" -type f -exec chmod 600 {} \;

cat <<EOF

Local runner secret folders are ready:
  $secret_root

Next:
  1. Copy keystore, Google Play JSON, App Store Connect .p8, and Apple Distribution .p12 files into the profile folders.
     App Store .mobileprovision files are selected by bundle id from ios/profiles/<bundle-id>.mobileprovision, or generated by fastlane sigh when IOS_PROVISIONING_PROFILE_AUTO_GENERATE=true.
  2. Fill these env files:
     - $secret_root/shared/android-signing.env
     - $secret_root/shared/ios-keychain.env
     - $secret_root/shared/github-package-read-token (optional, only when gh auth is unavailable)
     - $secret_root/profiles/actionfit/profile.env
     - $secret_root/profiles/actionfit/android-signing.env (optional override)
     - $secret_root/profiles/stormborn/profile.env
     - $secret_root/profiles/stormborn/android-signing.env (optional override)
  3. Validate:
     CI_SECRET_ROOT="$secret_root" bash Packages/com.actionfit.buildautomation/RunnerSetup/validate-local-runner-secrets.sh Actionfit Both GooglePlayInternalAndTestFlight
EOF
